version: "3.1"

services:
  test:
    image: "myunghyunnero/test:latest"
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      TZ: "Asia/Seoul"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: "unless-stopped"